=head1 NAME

pynag-maincfg - tool for editing nagios configuration files

=head1 SYNOPSIS

pynag-maincfg [attribute1=value1]...

=head1 DESCRIPTION

Pragmatic way to edit values in static nagios configuration
files like nagios.cfg

=head1 attributes

Updates or adds any valid configuration parameter in configuration
files like nagios.cfg and cgi.cfg.

=head1 ADDITIONAL RESOURCES

See http://code.google.com/p/pynag/ for more information.

=head1 SEE ALSO

pynag-safe_restart(1) pynag-add_host_to_group(1) pynag-addservice(1)
pynag-sql(1)

=head1 AUTHOR

Pall Sigurdsson <palli@opensource.is>
