=head1 NAME

pynag-safe_restart - Reloads nagios if the configuration is valid.

=head1 SYNOPSIS

pynag-safe_restart

=head1 DESCRIPTION

pynag-safe_restart verifies the nagios configuration and if the configuration
is succesfully verfified, nagios is reloaded to reflect changes.

=head1 ADDITIONAL RESOURCES

See http://code.google.com/p/pynag/ for more information.

=head1 SEE ALSO

pynag-add_host_to_group(1) pynag-addservice(1) pynag-maincfg(1)
pynag-sql(1)

=head1 AUTHOR

Drew Stinnett <drew@drewlink.com>
