=head1 NAME

pynag-sql - tool for editing nagios object in a SQL query style

=head1 SYNOPSIS

pynag-maincfg <sql statement>

=head1 DESCRIPTION

pynag-sql allows you to select object data from nagios using SQL
statements.

=head1 sql statement

SHOW tables
DESCRIBE <table>
SELECT <attributes> FROM <table> [WHERE <arguments>]

=head1 ADDITIONAL RESOURCES

See http://code.google.com/p/pynag/ for more information.

=head1 SEE ALSO

pynag-safe_restart(1) pynag-add_host_to_group(1) pynag-addservice(1)
pynag-maincfg(1)

=head1 AUTHOR

Pall Sigurdsson <palli@opensource.is>
