=head1 NAME

pynag-add_host_to_group - Adds a host to the specified nagios hostgoup

=head1 SYNOPSIS

pynag-add_host_to_group <hostname> <hostgroup_name>

=head1 DESCRIPTION

Adds the specified hostgroup to the host in question.

=head1 hostname

Hostname can be any correctly defined host in the nagios configuration.

=head1 hostgroup_name

hostgroup_name should be a valid hostgroup in the nagios configuration.

=head1 ADDITIONAL RESOURCES

See http://code.google.com/p/pynag/ for more information.

=head1 SEE ALSO

pynag-safe_restart(1) pynag-addservice(1) pynag-maincfg(1)
pynag-sql(1)

=head1 AUTHOR

Drew Stinnett <drew@drewlink.com>
